#!/bin/sh
clj -A:dev:codox
cp -r ./target/doc ../doctemp
git fetch origin gh-pages:gh-pages
git checkout gh-pages
cp -r ../doctemp/* ./
rm -rf ../doctemp
git add .
git commit -m "Regenerate documentation".
git push origin gh-pages
git checkout master
